[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "Calculator_dgudel"
version = "0.0.1"
authors = [
  { name="Dangis Gudelis", email="dgudel@gmail.com" },
]
description = "Calculator app"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
